### ISSUE TITLE
Firefox support 

### ISSUE THREAD

**Issue by SeriousM** [clmnin/summarize.site#1]
Would you add Firefox support? Your inspiration project is a good example!

**Comment by bossm0n5t3r** [comment]
@clmnin Do you have any plan for firefox extension support?

**Comment by clmnin** [comment]
@bossm0n5t3r I personally don't have the time to add firefox support at the moment. Maybe post April - I'm a bit engaged as I'm trying to bootstrap a small business. But you are free to fork the project and add FF support. It would be a great addition to the project.

**Comment by bossm0n5t3r** [comment]
Thank you for sharing your opinion and plan. I will also try to support FF, although I will be slower than others.

**Comment by clmnin** [comment]
Firefox support has been added in #17
