### ISSUE TITLE
do not work for other languages except English？

### ISSUE THREAD

**Issue by jarlin8** [clmnin/summarize.site#10]
as i test ,can only summarize  English site。in JP CN Ssite,not working.

**Comment by clmnin** [comment]
Hi @jarlin8 

The extension does work for other languages. You just have to modify the ChatGPT prompt to let it know your language of choice. I've added this in the [faq](https://github.com/clmnin/summarize.site#faq). But I've also added it below for your convenience

Q: How do I translate this to my language of choice?

* You can change the prompt in the options page
    * right click the extension in the toolbar
    * choose Options from the drop down menu
* The following two configurations have been [tested for Chinese](https://github.com/clmnin/summarize.site/issues/3#issuecomment-1340885865):
    * Rewrite this for brevity, translate into Chinese, in outline form:
        * This directly summarizes the article in Chinese, outline form.
    * Rewrite this for brevity, in outline form, Chinese translation:
        * This summarizes the article in outline form in English, and adds a Chinese translation below.
![image](https://user-images.githubusercontent.com/17064666/207025076-60dcf993-6a52-4e82-95f8-f1d571c5d9b0.png)

**Comment by clmnin** [comment]
This issue was fixed in 1832926cbf4909acff8008da6eba8c2005044749
