### ISSUE TITLE
Nothing else but login prompt in the Brave browser.

### ISSUE THREAD

**Issue by samuelgecik** [clmnin/summarize.site#12]
Hello, as title says, every time I try to run the extension I am getting only the login prompt. Even though I'm logged in.

**Comment by clmnin** [comment]
Try visiting chat.openai.com and make sure you are at the page where you can interact with ChatGPT. At times OpenAI will need to make sure you are not a bot and so you will see a page that says "Checking if the site connection is secure".
![image](https://user-images.githubusercontent.com/17064666/211160002-e769c300-a8cf-4157-9f91-692dd8921edc.png)

The extension only works if you have passed the "bot check". This may be the reason why you are unable go past the login prompt.

Please let me know if this was the reson.

**Comment by cryptotester** [comment]
I'm logged in and the extension always shows me:

Please login at [chat.openai.com](https://chat.openai.com/) first

I'm using Brave on Linux. Will uninstall the extension, as it doesn't work for me.

To compare, the YouTube summary extesion works fine, what it does is to send some text to a new tab with chatGPT in it. Works perfectly. Maybe you could use a similar approach instead of checking if the user is logged in or not.

**Comment by clmnin** [comment]
@cryptotester Yes, I think I should go with this approach. This way the extension does not have to deal with auth and throttling OpenAI does for its free users. Will start the work this weekend

**Comment by samuelgecik** [comment]
@cryptotester Sorry for the late response, I was very busy lately. However, I was definitely logged in properly. Today I reinstalled the extension and it worked, but only on the first try. Since then it gives me the login prompt on every other try.

**Comment by cryptotester** [comment]
> @cryptotester Yes, I think I should go with this approach. This way the extension does not have to deal with auth and throttling OpenAI does for its free users. Will start the work this weekend

In case, test this extension and see how it works: https://chrome.google.com/webstore/detail/youtube-summary-with-chat/nmmicjeknamkfloonkhhcjmomieiodli

I'm not sure what kind of "magic" it does behind the scenes, but I think when you click the transcript to expand it, then click the chatgpt button, it opens a new tab, then sends the text in the chat box or maybe the author found a javascrpt function to call in the new tab, not sure, maybe you can contact the author of that extension for a little hint (if this is not already documented online), works like a charm, just tested it now again.

Curious to test your extension when it's updated, thx & cheers

**Comment by clmnin** [comment]
OpenAI throttles free users. I don't think there is anything the extension can do for now. Closing as I don't think we can work around this.
