### ISSUE TITLE
ChatGPT call fails / times out

### ISSUE THREAD

**Issue by andrew-rosca** [clmnin/summarize.site#14]
See behavior here: https://www.loom.com/share/6ee08d195901479ebc10952d1784e9b4

I assume the issue is on the ChatGPT end and I speculate that there's a timeout that's causing the problem.

Is there any workaround?

**Comment by clmnin** [comment]
This happens in OpenAI's [ChatGPT interface](https://chat.openai.com/chat) too and it is **not something we can solve**. It is usually seen when they have a high demand / servers are overloaded. But I can't be sure.

Workarounds:
1. Simply refresh the page and try it again
2. Open a Chat GPT session in a new tab before you use the extension (summarize.site). 
    1. This will make sure your token is valid and Cloudflare's checks are completed. 
    2. This will give you a better change of a working extension

**Comment by andrew-rosca** [comment]
All of my attempts have failed, on various web pages. I've never seen the summarization complete successfully.

In contrast, if I go directly to the ChatGPT UI, I am able to paste the same web page text with the [prompt](https://github.com/clmnin/summarize.site/blob/1832926cbf4909acff8008da6eba8c2005044749/src/background/index.js#L7) and get a successful summarization.

I realize you may not have control over this and I was just wondering if the API has any kind of timeout parameter or something along those lines. I haven't read the code in detail yet but noticed that the response is streamed back and retrieved in chunks--perhaps there's a timeout in that code?

**Comment by clmnin** [comment]
Hm, I wasn't able to recreate this issue. Can you share a webpage where the extension times out?

**Comment by andrew-rosca** [comment]
Well, the page featured in the Loom video above is an example. I was able
to replicate just now:
https://www.msn.com/en-us/news/us/despite-everything-you-think-you-know-america-is-on-the-right-track/ar-AA16j5LD

**Comment by clmnin** [comment]
This issue was fixed in e44e24438a0e3929d2f1e9ef4374c7f3f809466f
