### ISSUE TITLE
Failed to load response from ChatGPT

### ISSUE THREAD

**Issue by robertoronderosjr** [clmnin/summarize.site#15]
As the extension starts receiving the summary I get:
Failed to load response from ChatGPT
![Screenshot 2023-01-23 150712](https://user-images.githubusercontent.com/4175612/214139100-af9d1532-416c-4eda-bfb9-9ee498a24077.jpg)

**Comment by clmnin** [comment]
With recent throttling and frequent auth token refreshes the extension has failed to work as expected.

A solution we could provide is to let you `copy` the content of the page you are on and let you `manually paste` it in ChatGPT input box. This way we can guarantee you get a summary. Just that it is a manual effort.

Would you @robertoronderosjr  be interested in this feature?

**Comment by robertoronderosjr** [comment]
yes a copy solution could be a workaround. However, I'd think that you could try adding code to mantain a fresh auth token (maybe with a web worker?) and slice API requests to avoid throttling?

**Comment by clmnin** [comment]
This issue was fixed in e44e24438a0e3929d2f1e9ef4374c7f3f809466f
