### ISSUE TITLE
Options do not update on Firefox

### ISSUE THREAD

**Issue by alexlyee** [clmnin/summarize.site#18]
Whenever I attempt to save anything in the plugin options on firefox it instantly disappears upon hitting save. I'm on the latest versions.

**Comment by bossm0n5t3r** [comment]
Did you build this firefox extension and attempt to save anything? it might be temporary addon ID issue.
(Error: The storage API will not work with a temporary addon ID. Please add an explicit addon ID to your manifest. For more information see https://mzl.la/3lPk1aE.)
(I saw this error after save in the plugin options on firefox)

Maybe this issue will be resolved when firefox version released to firefox add-ons.

Also, there is an error when "items" is undefind in firefox/public/options.js, so I will requet [PR](https://github.com/clmnin/summarize.site/pull/19) about this.
