### ISSUE TITLE
Images, videos, hyperlinks, etc. disappear when summarising a web page

### ISSUE THREAD

**Issue by Khoroamu** [clmnin/summarize.site#20]
As described in the title, when I try to summarize a web page, something in the page disappears:

![image](https://user-images.githubusercontent.com/74661149/230705908-3f53aabe-e1f9-4672-9e7c-bb1337074239.png)

**Comment by clmnin** [comment]
Hm, strange. I was able to recreate it too. Will take a look and give you an update. Thank you for reporting the issue.

Meanwhile if you find other websites where this issue can be recreated, please let me know.
