### ISSUE TITLE
cannot read Chinese contents

### ISSUE THREAD

**Issue by kulorro** [clmnin/summarize.site#22]
The extensions seems cannot read Chinese contents.

**Comment by clmnin** [comment]
Our default prompt is 

> You are acting as a summarization AI, and for the input text please summarize it to the most important 3 to 5 bullet points for brevity:

[Line 7 in background/index.js](https://github.com/clmnin/summarize.site/blob/master/chrome/src/background/index.js#L7)

Which does not consider for Chinese content. Please update this prompt to be something that tells ChatGPT your content is chinese (or any language of your choice). Here is a [prompt](https://github.com/clmnin/summarize.site/issues/3#issuecomment-1340885865) @wenlzhang used for the issue #3 .

To change the prompt you can do the following
* Right click the extension
* Select `Extension Options`
* Here you can modify the prompt to your choosing
    * example:
        * You are acting as a summarization AI, and for the input text please summarize it to the most important 3 to 5 bullet points for brevity, translated into Chinese:
