### ISSUE TITLE
[issues] the getContentOfArticle on content/index.js will break the website

### ISSUE THREAD

**Issue by ZoneTwelve** [clmnin/summarize.site#27]
- Environments: 
  - Chrome 114
  - Macbook Air M1

There is an issue with the extension functionality. Specifically, the getContentOfArticle has been called causing it to break the entire website.
Test on [YouTube](https://youtube.com)

files:
 - [lib/src/content/index.js](https://github.com/clmnin/summarize.site/blob/master/lib/src/content/index.js)

## Screenshot
![Screenshot 2023-08-18 at 11 07 07 PM](https://github.com/clmnin/summarize.site/assets/20425883/288d5b18-5c14-491a-a3fd-8b2180d4b6e2)

**Comment by ZoneTwelve** [comment]
but I going to fix this issues.

**Comment by clmnin** [comment]
@ZoneTwelve What is the issue here? `getContentOfArticle` works for me

**Comment by ZoneTwelve** [comment]
@clmnin I just updated the description of this issue.

**Comment by ZoneTwelve** [comment]
issues fix @ [PR 29](https://github.com/clmnin/summarize.site/pull/29)

**Comment by ZoneTwelve** [comment]
It would be best to disregard the package-lock.json file.

**Comment by clmnin** [comment]
Fixed in #29 

Thank you @ZoneTwelve
