### ISSUE TITLE
We need a new logo

### ISSUE THREAD

**Issue by clmnin** [clmnin/summarize.site#28]
The original chrome extension - [link](https://chrome.google.com/webstore/detail/summarize/lmhkmibdclhibdooglianggbnhcbcjeh/) was sold and so we need to differentiate this open source one from the closed source one.

And so we need a new logo

@ZoneTwelve any thing that we could used?

**Comment by ZoneTwelve** [comment]
Sounds good, I will try to design a new one for you.

**Comment by ZoneTwelve** [comment]
I've come to the conclusion that I shouldn't continue drawing.
![Summarize](https://github.com/clmnin/summarize.site/assets/20425883/e968586d-44a5-4bb6-a215-ee96b1703450)

**Comment by clmnin** [comment]
![logo-128](https://github.com/clmnin/summarize.site/assets/17064666/387592f9-bddc-41ae-9f3c-f2b1eb99b89c)

I'm going with this as it shows a ChatGPT logo and is similar to our previous logo
