### ISSUE TITLE
Restrictions

### ISSUE THREAD

**Issue by roygrubb** [clmnin/summarize.site#4]
I'm in Hong Kong

It tells me I can't access OpenAI from here.  But it accepted my account application from a HK IP address and a hk email address.

Is this a permanent restriction?

**Comment by clmnin** [comment]
I'm sorry, but it looks like OpenAI API isn't supported in your country. Here are the list of [supported countries and territories](https://beta.openai.com/docs/supported-countries/supported-countries-and-territories)
