### ISSUE TITLE
Summarise YouTube captions 

### ISSUE THREAD

**Issue by clmnin** [clmnin/summarize.site#7]
Would be a great feature for long form youtube videos like podcasts

**Comment by wenlzhang** [comment]
The following Chrome extension can be used to transcribe/extract YouTube videos as text.
https://ytscribe.com/

It might help with this feature implementation.

**Comment by wimdenherder** [comment]
For inspiration, this pull request works but was not accepted. I will be working on this later, but you can check it out here:

https://github.com/wong2/chat-gpt-google-extension/pull/142/commits/5e9d6ff10892a1625798045c5b4afb3832c4391a

**Comment by clmnin** [comment]
Out of scope
