### ISSUE TITLE
Support saving summaries as Markdown documents

### ISSUE THREAD

**Issue by wenlzhang** [clmnin/summarize.site#8]
It would be great if this can be supported. Or, there can be a button or something that allows to copy everything as Markdown to clipboard.

**Comment by wenlzhang** [comment]
> Or, there can be a button or something that allows to copy everything as Markdown to clipboard.

Even better, one can configure to copy the summary automatically to the clipboard after getting the summary.

**Comment by clmnin** [comment]
You can currently copy the text by simply dragging and selecting the text and <kbd>Ctrl</kbd> + <kbd>C</kbd>.

We don't have any extra style added to our summarized response and so `copying as markdown` would just be a simple text.

Can you please give us a solid example / usecase where you need this?

**Comment by wenlzhang** [comment]
> Can you please give us a solid example / usecase where you need this?

My use cases with this are as follows:

1. Sometimes, I would like to summarize a long article and save this summary as a backup into Obsidian.
2. Sometimes, I would like to save the article for reading later, and this summary can be used as a way to determine which article to read first.

Not sure if it is relevant, the following is a Chrome extension to save an article as Markdown.
https://blacksmithgu.github.io/obsidian-dataview/api/intro/

**Comment by clmnin** [comment]
You can now copy the content of the summary with the copy button. The data is already formatted to be in Markdown

This issue was fixed in efb78770e0f925aab973baa552468f3f682c7e64
