### ISSUE TITLE
help setting prompt in extension options:

### ISSUE THREAD

**Issue by GabrieleRisso** [clmnin/summarize.site#9]
first I wanted to say thanks for the amazing implementation. 

I wanted to konw if there are imporvements in utilizing other prompts other then the default  'Rewrite this for brevity, in outline form:'

thanks in advance.

**Comment by clmnin** [comment]
The default prompt works well. You can use a custom prompt as you find a usecase. For example currently we use it to translate the summarized response ( see issue #3 )
